os: linux
dist: trusty
language: node_js
node_js: lts/*

before_install: 
  - rvm install 2.2.2
  - gem install rubyzip
  - npm config set spin false

install: 
  - npm install

script:
  - npm run prod
  - npm run build:prod
