os: linux
dist: trusty
language: node_js

before_install: 
  - rvm install 2.2.2
  - gem install rubyzip
  - nvm install lts
  - nvm use lts/*
  - npm config set spin false

install: 
  - npm install

script:
  - npm run prod
  - npm run build:prod
